import { mkdirSync, mkdtempSync, realpathSync, rmSync, symlinkSync, utimesSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { loadConfig } from '../config/index.js';
import { getOutputDir, getWorkspaceAllowedRoots, getWorkspaceDir } from '../tools/workspace-policy.js';
import type { ArtifactEvent } from './types.js';
import { createTurnFileArtifactTracker, curateDeliverables } from './file-artifacts.js';
import type { FileArtifactData } from './file-artifacts.js';
import { ArtifactCoordinator } from './coordinator.js';

function previewUrl(route: '/api/fs/file' | '/api/fs/preview', path: string): string {
  return `${route}?${new URLSearchParams({ path }).toString()}`;
}

describe('artifacts/file-artifacts', () => {
  const savedMoziHome = process.env.MOZI_HOME;
  let moziHome: string;

  beforeEach(() => {
    moziHome = mkdtempSync(join(tmpdir(), 'mozi-file-artifacts-home-'));
    process.env.MOZI_HOME = moziHome;
    loadConfig('/nonexistent/mozi.json');
  });

  afterEach(() => {
    rmSync(moziHome, { recursive: true, force: true });
    if (savedMoziHome === undefined) {
      delete process.env.MOZI_HOME;
    } else {
      process.env.MOZI_HOME = savedMoziHome;
    }
    loadConfig('/nonexistent/mozi.json');
  });

  // Deliverable-shelf liveness (operator decision 2026-07-19, real incident:
  // the Brain rm -f'd a delivered PDF 39s after its card was emitted). A card
  // whose file vanishes is patched missing:true through the coordinator; if
  // the file reappears at the same path, the flag clears the same way.
  it('marks a carded deliverable missing when its file vanishes, and clears on reappearance', async () => {
    const outputDir = join(moziHome, 'output');
    mkdirSync(outputDir, { recursive: true });
    const pdfPath = join(outputDir, 'report.pdf');
    writeFileSync(pdfPath, '%PDF-1.4\ndelivered bytes');
    const future = new Date(Date.now() + 2_000);
    utimesSync(pdfPath, future, future);

    const artifactEvents: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-liveness', (event) => artifactEvents.push(event));
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });

    await tracker.scanAndEmit();
    const carded = artifactEvents.find(
      (event) => event.type === 'open' && (event.artifact.data as { filename?: string }).filename === 'report.pdf',
    );
    expect(carded).toBeTruthy();

    const lastPatchData = () => {
      const patch = artifactEvents.filter((event) => event.type === 'patch').at(-1);
      return (patch && patch.type === 'patch' ? patch.patch.data : undefined) as { missing?: boolean } | undefined;
    };

    rmSync(pdfPath);
    await tracker.scanAndEmit();
    expect(lastPatchData()?.missing).toBe(true);

    writeFileSync(pdfPath, '%PDF-1.4\nregenerated bytes');
    utimesSync(pdfPath, future, future);
    await tracker.scanAndEmit();
    // EXPLICIT false, never an absent key: store and client merge patch data
    // over existing data, so a missing key cannot clear a persisted `true`
    // (review finding 2026-07-19 — key-deletion left regenerated files
    // labeled "removed" forever).
    expect(lastPatchData()?.missing).toBe(false);
    expect((lastPatchData() as { filename?: string } | undefined)?.filename).toBe('report.pdf');
  });

  // Regression: a finished report sat in the workspace with no card at all while
  // its own research notes had cards. Shell's cwd is the workspace, so that is
  // where a script's relative path writes — and only `output` was ever scanned.
  it('cards a deliverable written to the workspace, but not MOZI own bookkeeping', async () => {
    const workspaceDir = getWorkspaceDir();
    const reportsDir = join(workspaceDir, 'reports');
    const tasksDir = join(workspaceDir, 'tasks');
    mkdirSync(reportsDir, { recursive: true });
    mkdirSync(tasksDir, { recursive: true });
    const reportPath = join(reportsDir, 'bond-report.pdf');
    const taskStatePath = join(tasksDir, 'task-notes.md');
    const scriptPath = join(workspaceDir, 'create_report.py');
    writeFileSync(reportPath, '%PDF-1.4\nreport bytes');
    writeFileSync(taskStatePath, '# runtime task state, not a deliverable');
    writeFileSync(scriptPath, 'print("this is how the report got made")');
    const future = new Date(Date.now() + 2_000);
    for (const path of [reportPath, taskStatePath, scriptPath]) {
      utimesSync(path, future, future);
    }

    const artifactEvents: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-workspace-scan', (event) => artifactEvents.push(event));
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });

    await tracker.scanAndEmit();

    const filenames = artifactEvents
      .filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open')
      .map((event) => String(event.artifact.data.filename));
    expect(filenames).toContain('bond-report.pdf');
    expect(filenames).not.toContain('task-notes.md');
    expect(filenames).not.toContain('create_report.py');
  });

  // Opt-in minting doctrine (operator decision 2026-07-19). Real incident: a
  // dataset-analysis turn carded 74 artifacts — the downloaded archive, the
  // extracted 540k-row xlsx, every intermediate chart png — and the chat showed
  // "68 supporting files" under the report. Working material in MOZI's scratch
  // space is process, not product: only the `output/` shelf and primary-eligible
  // documents mint cards from the recursive scan.
  it('does not card workspace working material — only primary-eligible documents', async () => {
    const workspaceDir = getWorkspaceDir();
    const outputDir = getOutputDir();
    mkdirSync(workspaceDir, { recursive: true });
    mkdirSync(outputDir, { recursive: true });
    const junkPaths = ['dataset.zip', 'chart.png', 'extract.csv', 'notes.md'].map((n) => join(workspaceDir, n));
    const reportPath = join(workspaceDir, 'report.pdf');
    const shelfPngPath = join(outputDir, 'shelf-chart.png');
    junkPaths.forEach((p, i) => writeFileSync(p, Buffer.from([0x50, 0x4b, 0x03, i])));
    writeFileSync(reportPath, '%PDF-1.4\nreport bytes');
    writeFileSync(shelfPngPath, Buffer.from([0x89, 0x50, 0x4e, 0x47]));
    const future = new Date(Date.now() + 2_000);
    for (const p of [...junkPaths, reportPath, shelfPngPath]) utimesSync(p, future, future);

    const events: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-optin-scan', (event) => events.push(event));
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });

    await tracker.scanAndEmit();

    const filenames = events
      .filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open')
      .map((event) => String(event.artifact.data.filename))
      .sort();
    // The cwd-report backstop survives; the shelf mints everything recognized.
    expect(filenames).toEqual(['report.pdf', 'shelf-chart.png']);
  });

  it('does not card a workspace dataset xlsx once the turn authored a rich deliverable', async () => {
    // The UCI Online Retail shape exactly: report authored as a rich artifact,
    // dataset downloaded into the workspace. The xlsx loses primary eligibility
    // to the rich deliverable and must not mint at all — previously it carded
    // and was merely demoted to supporting noise.
    const workspaceDir = getWorkspaceDir();
    mkdirSync(workspaceDir, { recursive: true });
    const datasetPath = join(workspaceDir, 'Online_Retail.xlsx');
    writeFileSync(datasetPath, 'xlsx dataset bytes');
    const future = new Date(Date.now() + 2_000);
    utimesSync(datasetPath, future, future);

    const events: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-optin-rich', (event) => events.push(event));
    coordinator.openOrGet('call-report', {
      plugin_id: 'sandpack_v1',
      title: 'Analytics report',
      content_type: 'html',
      status: 'running',
      data: { code: '<!doctype html><html><body>report</body></html>', content_type: 'html' },
    });
    coordinator.complete('call-report', {});
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });

    await tracker.scanAndEmit();

    const opens = events.filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open');
    expect(opens.map((event) => String(event.artifact.data.filename))).not.toContain('Online_Retail.xlsx');
  });

  it('still cards workspace working material when explicitly reported (declaration beats location)', async () => {
    const workspaceDir = getWorkspaceDir();
    mkdirSync(workspaceDir, { recursive: true });
    const chartPath = join(workspaceDir, 'declared-chart.png');
    writeFileSync(chartPath, Buffer.from([0x89, 0x50, 0x4e, 0x47]));

    const events: ArtifactEvent[] = [];
    const tracker = createTurnFileArtifactTracker({
      artifactCoordinator: new ArtifactCoordinator('turn-optin-explicit', (event) => events.push(event)),
    });

    await tracker.emitPaths([chartPath]);

    const opens = events.filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open');
    expect(opens.map((event) => String(event.artifact.data.filename))).toEqual(['declared-chart.png']);
  });

  it('does not claim a pre-existing output decoy when a workspace deliverable is produced', async () => {
    const outputDir = getOutputDir();
    const workspaceDir = getWorkspaceDir();
    mkdirSync(outputDir, { recursive: true });
    const decoyPath = join(outputDir, 'US_Macro_Bond_Report.pdf');
    const reportPath = join(workspaceDir, 'actual-report.pdf');
    writeFileSync(decoyPath, '%PDF-1.4\nexternal decoy');

    const events: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-decoy-boundary', (event) => events.push(event));
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });
    await tracker.captureBaseline();

    writeFileSync(reportPath, '%PDF-1.4\nactual report');
    const future = new Date(Date.now() + 2_000);
    utimesSync(reportPath, future, future);
    await tracker.scanAndEmit();

    const filenames = events
      .filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open')
      .map((event) => String(event.artifact.data.filename));
    expect(filenames).toEqual(['actual-report.pdf']);
  });

  it('adds honest preview fields to file_v1 artifacts', async () => {
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    const pptxPath = join(outputDir, 'deck.pptx');
    const pdfPath = join(outputDir, 'report.pdf');
    const pngPath = join(outputDir, 'chart.png');
    const txtPath = join(outputDir, 'notes.txt');
    const xlsxPath = join(outputDir, 'budget.xlsx');
    const unknownPath = join(outputDir, 'design.sketch');
    const artifactEvents: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-preview-fields', (event) => artifactEvents.push(event));
    const tracker = createTurnFileArtifactTracker({
      artifactCoordinator: coordinator,
    });

    writeFileSync(pptxPath, 'pptx bytes');
    writeFileSync(pdfPath, '%PDF-1.4\npdf bytes');
    writeFileSync(pngPath, Buffer.from([0x89, 0x50, 0x4e, 0x47]));
    writeFileSync(txtPath, 'plain text');
    writeFileSync(xlsxPath, 'xlsx bytes');
    writeFileSync(unknownPath, 'unknown deliverable');
    const future = new Date(Date.now() + 2_000);
    for (const path of [pptxPath, pdfPath, pngPath, txtPath, xlsxPath, unknownPath]) {
      utimesSync(path, future, future);
    }

    await tracker.scanAndEmit();

    const dataByFilename = new Map(
      artifactEvents
        .filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open')
        .map((event) => [String(event.artifact.data.filename), event.artifact.data]),
    );
    const quickLookAvailable = process.platform === 'darwin';

    expect(dataByFilename.get('deck.pptx')).toMatchObject({
      path: realpathSync(pptxPath),
      ext: 'pptx',
      kind: 'deck',
      previewable: quickLookAvailable,
      ...(quickLookAvailable ? { previewUrl: previewUrl('/api/fs/preview', realpathSync(pptxPath)) } : {}),
      downloadUrl: previewUrl('/api/fs/file', realpathSync(pptxPath)),
    });
    if (!quickLookAvailable) {
      expect(dataByFilename.get('deck.pptx')?.previewUrl).toBeUndefined();
    }

    expect(dataByFilename.get('report.pdf')).toMatchObject({
      path: realpathSync(pdfPath),
      ext: 'pdf',
      kind: 'document',
      previewable: quickLookAvailable,
      ...(quickLookAvailable ? { previewUrl: previewUrl('/api/fs/preview', realpathSync(pdfPath)) } : {}),
    });
    if (!quickLookAvailable) {
      expect(dataByFilename.get('report.pdf')?.previewUrl).toBeUndefined();
    }

    expect(dataByFilename.get('chart.png')).toMatchObject({
      path: realpathSync(pngPath),
      ext: 'png',
      kind: 'image',
      previewable: true,
      previewUrl: previewUrl('/api/fs/file', realpathSync(pngPath)),
    });

    expect(dataByFilename.get('notes.txt')).toMatchObject({
      path: realpathSync(txtPath),
      ext: 'txt',
      kind: 'document',
      previewable: false,
    });
    expect(dataByFilename.get('notes.txt')?.previewUrl).toBeUndefined();
    expect(dataByFilename.get('budget.xlsx')).toMatchObject({
      path: realpathSync(xlsxPath),
      ext: 'xlsx',
      kind: 'sheet',
      downloadUrl: previewUrl('/api/fs/file', realpathSync(xlsxPath)),
    });
    expect(dataByFilename.get('design.sketch')).toBeUndefined();
  });

  it('emits an explicitly reported worker artifact even when it predates the turn scan', async () => {
    const workspaceRoot = getOutputDir();
    expect(getWorkspaceAllowedRoots()).toContain(workspaceRoot);
    mkdirSync(workspaceRoot, { recursive: true });
    const reportPath = join(workspaceRoot, 'worker-report.docx');
    writeFileSync(reportPath, 'docx bytes');
    const events: ArtifactEvent[] = [];
    const tracker = createTurnFileArtifactTracker({
      activeRootPath: workspaceRoot,
      artifactCoordinator: new ArtifactCoordinator('turn-worker-file', event => events.push(event)),
    });

    await tracker.emitPaths([reportPath, reportPath]);

    const opens = events.filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open');
    expect(opens).toHaveLength(1);
    expect(opens[0].artifact.data).toMatchObject({
      path: realpathSync(reportPath),
      filename: 'worker-report.docx',
      downloadUrl: previewUrl('/api/fs/file', realpathSync(reportPath)),
    });
  });

  it('does not scan an active-root symlink whose real target is outside allowed roots', async () => {
    const grantedRoot = mkdtempSync(join(tmpdir(), 'mozi-file-artifacts-granted-'));
    const outsideRoot = mkdtempSync(join(tmpdir(), 'mozi-file-artifacts-outside-'));
    try {
      const configPath = join(moziHome, 'symlink-root-config.json');
      writeFileSync(configPath, JSON.stringify({
        tools: { fs: { additional_allowed_roots: [grantedRoot] } },
      }));
      loadConfig(configPath);

      const linkedProject = join(grantedRoot, 'linked-project');
      const outsideReport = join(outsideRoot, 'outside-report.pdf');
      writeFileSync(outsideReport, '%PDF-1.4\noutside');
      symlinkSync(outsideRoot, linkedProject, 'dir');

      const events: ArtifactEvent[] = [];
      const tracker = createTurnFileArtifactTracker({
        activeRootPath: linkedProject,
        artifactCoordinator: new ArtifactCoordinator('turn-symlink-root', event => events.push(event)),
      });
      await tracker.scanAndEmit();

      expect(events.filter(event => event.type === 'open')).toHaveLength(0);
    } finally {
      rmSync(grantedRoot, { recursive: true, force: true });
      rmSync(outsideRoot, { recursive: true, force: true });
    }
  });

  it('keeps explicit Python deliverables from a project nested in the workspace', async () => {
    const projectRoot = join(getWorkspaceDir(), 'active-project');
    mkdirSync(projectRoot, { recursive: true });
    const scriptPath = join(projectRoot, 'analysis.py');
    writeFileSync(scriptPath, 'print("deliverable")\n');

    const events: ArtifactEvent[] = [];
    const tracker = createTurnFileArtifactTracker({
      activeRootPath: projectRoot,
      artifactCoordinator: new ArtifactCoordinator('turn-nested-project-code', event => events.push(event)),
    });
    await tracker.emitPaths([scriptPath]);

    const opens = events.filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open');
    expect(opens).toHaveLength(1);
    expect(opens[0].artifact.data).toMatchObject({
      path: realpathSync(scriptPath),
      filename: 'analysis.py',
      kind: 'code',
    });
  });

  it.each([
    ['xlsx', 'Q2___________-2.xlsx', '2026Q2_12国税务动态.xlsx'],
    ['pdf', '____________.pdf', '2026年Q2税务动态.pdf'],
  ])('converges byte-identical %s deliverables to the newest human-readable filename', async (
    extension,
    placeholderName,
    finalName,
  ) => {
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    const placeholderPath = join(outputDir, placeholderName);
    const finalPath = join(outputDir, finalName);
    const bytes = `identical ${extension} bytes`;
    const events: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator(`turn-content-dedupe-${extension}`, event => events.push(event));
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });

    writeFileSync(placeholderPath, bytes);
    utimesSync(placeholderPath, new Date(Date.now() + 1_000), new Date(Date.now() + 1_000));
    await tracker.scanAndEmit();

    writeFileSync(finalPath, bytes);
    utimesSync(finalPath, new Date(Date.now() + 2_000), new Date(Date.now() + 2_000));
    await tracker.scanAndEmit();

    const opens = events.filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open');
    const patches = events.filter((event): event is Extract<ArtifactEvent, { type: 'patch' }> => event.type === 'patch');
    expect(opens).toHaveLength(1);
    expect(patches.at(-1)).toMatchObject({
      artifactId: opens[0].artifact.id,
      patch: {
        title: finalName,
        data: {
          path: realpathSync(finalPath),
          filename: finalName,
        },
      },
    });
    expect(coordinator.resolveByPath(realpathSync(placeholderPath))).toBe(opens[0].artifact.id);
    expect(coordinator.resolveByPath(realpathSync(finalPath))).toBe(opens[0].artifact.id);
  });

  it('keeps same-size deliverables separate when their bytes differ', async () => {
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    const firstPath = join(outputDir, '华东报告.pdf');
    const secondPath = join(outputDir, '华南报告.pdf');
    const events: ArtifactEvent[] = [];
    const tracker = createTurnFileArtifactTracker({
      artifactCoordinator: new ArtifactCoordinator('turn-no-false-dedupe', event => events.push(event)),
    });

    writeFileSync(firstPath, 'region-east');
    writeFileSync(secondPath, 'region-south');
    const future = new Date(Date.now() + 2_000);
    utimesSync(firstPath, future, future);
    utimesSync(secondPath, future, future);

    await tracker.scanAndEmit();

    const titles = events
      .filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open')
      .map(event => event.artifact.title);
    expect(titles).toEqual(['华东报告.pdf', '华南报告.pdf']);
  });

  it('skips file_v1 when the same realpath was surfaced as a rich artifact this turn', async () => {
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    const htmlPath = join(outputDir, 'deck.html');
    const pptxPath = join(outputDir, 'deck.pptx');
    const artifactEvents: ArtifactEvent[] = [];
    const richArtifactPaths = new Set<string>();
    const coordinator = new ArtifactCoordinator('turn-rich-skip', (event) => artifactEvents.push(event));
    const tracker = createTurnFileArtifactTracker({
      richArtifactPaths,
      artifactCoordinator: coordinator,
    });

    writeFileSync(htmlPath, '<!doctype html><html><body>Deck</body></html>');
    writeFileSync(pptxPath, 'pptx bytes');
    const future = new Date(Date.now() + 2_000);
    for (const path of [htmlPath, pptxPath]) {
      utimesSync(path, future, future);
    }
    richArtifactPaths.add(realpathSync(htmlPath));

    await tracker.scanAndEmit();

    const fileArtifactTitles = artifactEvents
      .filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open')
      .map((event) => event.artifact.title);

    expect(fileArtifactTitles).toEqual(['deck.pptx']);
  });

  it('does not auto-publish build metadata, cache files, or generator source', async () => {
    const outputDir = getOutputDir();
    const targetDir = join(outputDir, 'target', 'debug', '.fingerprint', 'crate');
    mkdirSync(targetDir, { recursive: true });
    mkdirSync(outputDir, { recursive: true });
    const reportPath = join(outputDir, 'report.docx');
    writeFileSync(reportPath, 'docx bytes');
    writeFileSync(join(outputDir, 'generate_report.js'), 'console.log("intermediate")');
    writeFileSync(join(targetDir, 'build_script_build-deadbeef.d'), 'metadata');
    writeFileSync(join(targetDir, 'invoked.timestamp'), 'timestamp');
    const future = new Date(Date.now() + 2_000);
    utimesSync(reportPath, future, future);
    utimesSync(join(outputDir, 'generate_report.js'), future, future);
    const events: ArtifactEvent[] = [];
    const tracker = createTurnFileArtifactTracker({
      artifactCoordinator: new ArtifactCoordinator('turn-filter-build-files', event => events.push(event)),
    });

    await tracker.scanAndEmit();

    const titles = events
      .filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open')
      .map(event => event.artifact.title);
    expect(titles).toEqual(['report.docx']);
  });

  it('still publishes an explicitly reported uncommon file', async () => {
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    const explicitPath = join(outputDir, 'result.custom');
    writeFileSync(explicitPath, 'custom result');
    const events: ArtifactEvent[] = [];
    const tracker = createTurnFileArtifactTracker({
      artifactCoordinator: new ArtifactCoordinator('turn-explicit-custom-file', event => events.push(event)),
    });

    await tracker.emitPaths([explicitPath]);

    const open = events.find((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open');
    expect(open?.artifact.title).toBe('result.custom');
  });

  it('converges a write_file-owned pptx with the output scan by registered path', async () => {
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    const pptxPath = join(outputDir, 'owned-deck.pptx');
    const artifactEvents: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-file-convergence', (event) => artifactEvents.push(event));
    const tracker = createTurnFileArtifactTracker({
      artifactCoordinator: coordinator,
    });

    writeFileSync(pptxPath, 'pptx bytes');
    const future = new Date(Date.now() + 2_000);
    utimesSync(pptxPath, future, future);

    const artifactId = coordinator.openOrGet('write-pptx', {
      plugin_id: 'file_v1',
      title: 'owned-deck.pptx',
      content_type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      status: 'running',
      fallback_text: 'File ready: owned-deck.pptx',
      data: {
        path: realpathSync(pptxPath),
        filename: 'owned-deck.pptx',
        ext: 'pptx',
        size: Buffer.byteLength('pptx bytes'),
        mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        kind: 'deck',
        previewable: false,
      },
    });
    coordinator.registerFileWrite('write-pptx', realpathSync(pptxPath));
    coordinator.complete('write-pptx', {
      plugin_id: 'file_v1',
      title: 'owned-deck.pptx',
      data: {
        path: realpathSync(pptxPath),
        filename: 'owned-deck.pptx',
        ext: 'pptx',
        size: Buffer.byteLength('pptx bytes'),
        mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        kind: 'deck',
        previewable: false,
      },
    });

    await tracker.scanAndEmit();

    const opens = artifactEvents.filter((event): event is Extract<ArtifactEvent, { type: 'open' }> => event.type === 'open');
    const scanPatch = artifactEvents.find((event): event is Extract<ArtifactEvent, { type: 'patch' }> => (
      event.type === 'patch' &&
      event.artifactId === artifactId &&
      event.patch.plugin_id === 'file_v1' &&
      event.patch.data?.path === realpathSync(pptxPath)
    ));

    expect(opens).toHaveLength(1);
    expect(opens[0].artifact.id).toBe(artifactId);
    expect(scanPatch?.artifactId).toBe(artifactId);
  });

  it('demotes render frames to supporting and leads with the primary deliverable', async () => {
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    const pptxPath = join(outputDir, 'GPT-5.6_deck.pptx');
    const pdfPath = join(outputDir, 'GPT-5.6_deck.pdf');
    const slidePaths = ['slide-01.jpg', 'slide-02.jpg', 'slide-03.jpg'].map((n) => join(outputDir, n));
    const events: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-curate', (event) => events.push(event));
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });

    writeFileSync(pptxPath, 'pptx bytes');
    writeFileSync(pdfPath, '%PDF-1.4\npdf bytes');
    // Distinct bytes per frame: byte-identical files are intentionally deduped
    // to a single artifact within a turn, which would mask the role assertion.
    slidePaths.forEach((p, i) => writeFileSync(p, Buffer.from([0xff, 0xd8, 0xff, i])));
    const future = new Date(Date.now() + 2_000);
    for (const p of [pptxPath, pdfPath, ...slidePaths]) utimesSync(p, future, future);

    await tracker.scanAndEmit();

    const opens = events.filter((e): e is Extract<ArtifactEvent, { type: 'open' }> => e.type === 'open');
    const roleOf = (name: string) => opens.find((e) => e.artifact.data.filename === name)?.artifact.data.role;

    // Deck leads, then the derived PDF.
    expect(opens.filter((e) => e.artifact.data.role === 'primary').map((e) => String(e.artifact.data.filename)))
      .toEqual(['GPT-5.6_deck.pptx', 'GPT-5.6_deck.pdf']);
    // The render batch stays durable but collapses behind the deliverable — it
    // is no longer dropped outright, so the user can still reach it.
    for (const frame of ['slide-01.jpg', 'slide-02.jpg', 'slide-03.jpg']) {
      expect(roleOf(frame), frame).toBe('supporting');
    }
  });

  it('demotes co-produced charts regardless of how they are named', async () => {
    // The production case: charts embedded in a report were published as sibling
    // cards because their names did not match an anticipated frame pattern.
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    const pdfPath = join(outputDir, 'US_Macro_Bond_Report_20260715.pdf');
    const chartPaths = [
      'chart1_yield_curve.png',
      'chart2_scenario_impact.png',
      'chart5_curve_snapshot.png',
    ].map((n) => join(outputDir, n));
    const events: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-charts', (event) => events.push(event));
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });

    writeFileSync(pdfPath, '%PDF-1.4\npdf bytes');
    chartPaths.forEach((p, i) => writeFileSync(p, Buffer.from([0x89, 0x50, 0x4e, 0x47, i])));
    const future = new Date(Date.now() + 2_000);
    for (const p of [pdfPath, ...chartPaths]) utimesSync(p, future, future);

    await tracker.scanAndEmit();

    const opens = events.filter((e): e is Extract<ArtifactEvent, { type: 'open' }> => e.type === 'open');
    const primary = opens.filter((e) => e.artifact.data.role === 'primary').map((e) => String(e.artifact.data.filename));
    const supporting = opens.filter((e) => e.artifact.data.role === 'supporting').map((e) => String(e.artifact.data.filename));

    expect(primary).toEqual(['US_Macro_Bond_Report_20260715.pdf']);
    expect(supporting).toEqual(expect.arrayContaining([
      'chart1_yield_curve.png',
      'chart2_scenario_impact.png',
      'chart5_curve_snapshot.png',
    ]));
  });

  it('demotes charts published before the report existed', async () => {
    // Files are scanned after each tool batch, so a turn that renders charts in
    // one step and assembles the report in the next publishes the charts while
    // no deliverable exists yet. They must not stay presented as deliverables.
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    const chartPath = join(outputDir, 'chart1_yield_curve.png');
    const pdfPath = join(outputDir, 'report.pdf');
    const events: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-late-doc', (event) => events.push(event));
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });

    // Batch 1: the chart only.
    writeFileSync(chartPath, Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x01]));
    utimesSync(chartPath, new Date(Date.now() + 1_000), new Date(Date.now() + 1_000));
    await tracker.scanAndEmit();

    const opens = events.filter((e): e is Extract<ArtifactEvent, { type: 'open' }> => e.type === 'open');
    expect(opens.map((e) => String(e.artifact.data.filename))).toEqual(['chart1_yield_curve.png']);
    // Nothing outranked it at the time, so it opened as a deliverable.
    expect(opens[0].artifact.data.role).toBeUndefined();

    // Batch 2: the report the chart was made for.
    writeFileSync(pdfPath, '%PDF-1.4\nreport');
    utimesSync(pdfPath, new Date(Date.now() + 2_000), new Date(Date.now() + 2_000));
    await tracker.scanAndEmit();

    const chartArtifactId = opens[0].artifact.id;
    const demotion = events
      .filter((e): e is Extract<ArtifactEvent, { type: 'patch' }> => e.type === 'patch')
      .findLast((e) => e.artifactId === chartArtifactId);
    expect(demotion?.patch.data).toMatchObject({ role: 'supporting' });
  });

  it('demotes co-produced files when the turn authored a document_v1 report (Issue #735)', async () => {
    // The Brain writes the report via create_artifact (document_v1), which never
    // passes through the filesystem scan. The tracker's primary-deliverable
    // latch must still see it — the two deliverable paths share one role
    // contract, so the charts rendered beside the report collapse to supporting.
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    const chartPath = join(outputDir, 'chart_growth.png');
    const events: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-brain-doc', (event) => events.push(event));
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });

    // Batch 1: the chart only — nothing outranks it yet.
    writeFileSync(chartPath, Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x01]));
    utimesSync(chartPath, new Date(Date.now() + 1_000), new Date(Date.now() + 1_000));
    await tracker.scanAndEmit();
    const opens = events.filter((e): e is Extract<ArtifactEvent, { type: 'open' }> => e.type === 'open');
    expect(opens.map((e) => String(e.artifact.data.filename))).toEqual(['chart_growth.png']);
    expect(opens[0].artifact.data.role).toBeUndefined();

    // Batch 2: the Brain authors the report as document_v1. Only a COMPLETED
    // document counts — create_artifact completes its card within the same
    // tool call, before the next scan runs.
    coordinator.openOrGet('call-doc', {
      plugin_id: 'document_v1',
      title: 'Growth report',
      content_type: 'markdown',
      status: 'running',
      data: { markdown: '# Growth', content_type: 'markdown' },
    });
    await tracker.scanAndEmit();
    // Still streaming → no demotion yet.
    expect(events.some((e) => e.type === 'patch'
      && (e.patch.data as Record<string, unknown> | undefined)?.role === 'supporting')).toBe(false);

    coordinator.complete('call-doc', { data: { markdown: '# Growth', content_type: 'markdown' } });
    await tracker.scanAndEmit();

    const chartArtifactId = opens[0].artifact.id;
    const demotion = events
      .filter((e): e is Extract<ArtifactEvent, { type: 'patch' }> => e.type === 'patch')
      .findLast((e) => e.artifactId === chartArtifactId);
    expect(demotion?.patch.data).toMatchObject({ role: 'supporting' });
  });

  it('does not let a scratch note demote the charts the user asked for', async () => {
    // `.md`/`.txt` are classified as `document`, so treating every document kind
    // as a deliverable meant a throwaway summary.md would collapse the five
    // charts that were the actual request behind it.
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    const notePath = join(outputDir, 'summary.md');
    const chartPaths = ['plot_a.png', 'plot_b.png'].map((n) => join(outputDir, n));
    const events: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-scratch-note', (event) => events.push(event));
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });

    writeFileSync(notePath, '# notes');
    chartPaths.forEach((p, i) => writeFileSync(p, Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x10 + i])));
    const future = new Date(Date.now() + 2_000);
    for (const p of [notePath, ...chartPaths]) utimesSync(p, future, future);

    await tracker.scanAndEmit();

    const opens = events.filter((e): e is Extract<ArtifactEvent, { type: 'open' }> => e.type === 'open');
    for (const e of opens) expect(e.artifact.data.role, String(e.artifact.data.filename)).toBeUndefined();
  });

  it('keeps standalone images primary when there is no primary document deliverable', async () => {
    const outputDir = getOutputDir();
    mkdirSync(outputDir, { recursive: true });
    // A render-frame name, but no deck present: charts may be the actual request.
    const imgPath = join(outputDir, 'slide-01.jpg');
    const events: ArtifactEvent[] = [];
    const coordinator = new ArtifactCoordinator('turn-standalone-img', (event) => events.push(event));
    const tracker = createTurnFileArtifactTracker({ artifactCoordinator: coordinator });

    writeFileSync(imgPath, Buffer.from([0xff, 0xd8, 0xff]));
    const future = new Date(Date.now() + 2_000);
    utimesSync(imgPath, future, future);

    await tracker.scanAndEmit();

    const opens = events.filter((e): e is Extract<ArtifactEvent, { type: 'open' }> => e.type === 'open');
    const img = opens.find((e) => e.artifact.data.filename === 'slide-01.jpg');
    expect(img).toBeDefined();
    // Nothing to demote it behind, so it must not be hidden.
    expect(img?.artifact.data.role).toBeUndefined();
  });

  describe('cross-turn artifact identity', () => {
    it('does not republish a file an earlier turn of the session already published', async () => {
      // The production shape: a plan hands the deliverable to a background turn,
      // which generates and publishes the PDF; the foreground turn's end-of-turn
      // scan then finds the same file on the shared output dir. Both minted their
      // own artifact id and the user saw the same 33KB document twice.
      const outputDir = getOutputDir();
      mkdirSync(outputDir, { recursive: true });
      const pdfPath = join(outputDir, 'US_Macro_Bond_Report.pdf');
      writeFileSync(pdfPath, '%PDF-1.4\nreport bytes');
      const future = new Date(Date.now() + 2_000);
      utimesSync(pdfPath, future, future);

      const events: ArtifactEvent[] = [];
      const tracker = createTurnFileArtifactTracker({
        artifactCoordinator: new ArtifactCoordinator('turn-foreground', (event) => events.push(event)),
        // Stands in for the durable timeline: the background turn's card.
        resolvePublishedArtifactId: (path) => (path === realpathSync(pdfPath) ? 'file_from_background_turn' : null),
      });

      await tracker.scanAndEmit();

      // One card, not two: this turn takes over the background turn's artifact
      // instead of minting a second id for the same file.
      expect(events.filter((e) => e.type === 'open')).toHaveLength(0);
      const patches = events.filter((e): e is Extract<ArtifactEvent, { type: 'patch' }> => e.type === 'patch');
      expect(patches.map((p) => p.artifactId)).toContain('file_from_background_turn');
    });

    it('still publishes a file no earlier turn produced', async () => {
      const outputDir = getOutputDir();
      mkdirSync(outputDir, { recursive: true });
      const pdfPath = join(outputDir, 'fresh_report.pdf');
      writeFileSync(pdfPath, '%PDF-1.4\nfresh');
      const future = new Date(Date.now() + 2_000);
      utimesSync(pdfPath, future, future);

      const events: ArtifactEvent[] = [];
      const tracker = createTurnFileArtifactTracker({
        artifactCoordinator: new ArtifactCoordinator('turn-fresh', (event) => events.push(event)),
        resolvePublishedArtifactId: () => null,
      });

      await tracker.scanAndEmit();

      const opens = events.filter((e): e is Extract<ArtifactEvent, { type: 'open' }> => e.type === 'open');
      expect(opens.map((e) => String(e.artifact.data.filename))).toEqual(['fresh_report.pdf']);
    });

    it('updates the existing card when a later turn regenerates the same path', async () => {
      // The case suppression got wrong: turn 2 regenerates report.pdf. Skipping
      // it left that turn showing no card at all. Adopting patches the card the
      // earlier turn published — one card, and it reflects the new content.
      const outputDir = getOutputDir();
      mkdirSync(outputDir, { recursive: true });
      const pdfPath = join(outputDir, 'owned_report.pdf');
      const events: ArtifactEvent[] = [];
      const tracker = createTurnFileArtifactTracker({
        artifactCoordinator: new ArtifactCoordinator('turn-two', (event) => events.push(event)),
        resolvePublishedArtifactId: () => 'file_from_turn_one',
      });

      writeFileSync(pdfPath, '%PDF-1.4\nv2 regenerated with Q3 numbers');
      utimesSync(pdfPath, new Date(Date.now() + 2_000), new Date(Date.now() + 2_000));
      await tracker.scanAndEmit();

      // No second card...
      expect(events.filter((e) => e.type === 'open')).toHaveLength(0);
      // ...but the first turn's card is updated rather than left stale or silent.
      const patches = events.filter((e): e is Extract<ArtifactEvent, { type: 'patch' }> => e.type === 'patch');
      expect(patches.map((p) => p.artifactId)).toContain('file_from_turn_one');
      expect(patches.at(-1)?.patch.data).toMatchObject({ filename: 'owned_report.pdf' });
    });
  });
});

describe('artifacts/file-artifacts — primary eligibility narrows under a rich deliverable (G2)', () => {
  const candidate = (overrides: Partial<FileArtifactData>) => ({
    data: {
      path: `/out/${overrides.filename ?? 'f'}`,
      filename: 'f',
      ext: 'xlsx',
      size: 10,
      mime: 'application/octet-stream',
      kind: 'sheet' as const,
      previewable: false,
      downloadUrl: '/api/fs/file?path=x',
      ...overrides,
    },
    mtimeMs: 1,
    ctimeMs: 1,
  });

  it('keeps extension-based primary when the turn authored no rich deliverable', () => {
    const roled = curateDeliverables([
      candidate({ filename: 'Online_Retail.xlsx', ext: 'xlsx', kind: 'sheet' }),
      candidate({ filename: 'clean.csv', ext: 'csv', kind: 'sheet' }),
    ]);
    expect(roled.find((c) => c.data.filename === 'Online_Retail.xlsx')?.data.role).toBe('primary');
    expect(roled.find((c) => c.data.filename === 'clean.csv')?.data.role).toBe('supporting');
  });

  it('demotes data sheets to supporting when the turn authored a rich deliverable (raw-dataset incident)', () => {
    // Real incident 2026-07-18: a downloaded Online_Retail.xlsx hero-carded as
    // `primary` beside the sandpack report that WAS the deliverable.
    const roled = curateDeliverables([
      candidate({ filename: 'Online_Retail.xlsx', ext: 'xlsx', kind: 'sheet' }),
      candidate({ filename: 'clean.csv', ext: 'csv', kind: 'sheet' }),
    ], false, true);
    expect(roled.every((c) => c.data.role === 'supporting')).toBe(true);
  });

  it('lets real document deliverables (PDF/PPTX) keep primary beside a rich deliverable', () => {
    const roled = curateDeliverables([
      candidate({ filename: 'report.pdf', ext: 'pdf', kind: 'document' }),
      candidate({ filename: 'source.xlsx', ext: 'xlsx', kind: 'sheet' }),
    ], false, true);
    expect(roled.find((c) => c.data.filename === 'report.pdf')?.data.role).toBe('primary');
    expect(roled.find((c) => c.data.filename === 'source.xlsx')?.data.role).toBe('supporting');
  });
});
